from helper.imports.packageImports import np
dataSets = {
    "car": {
        "trainPath": "./car/train.csv", 
        "testPath": "./car/test.csv",
        "attrNames": ["buying","maint","doors","persons","lug_boot","safety","label"],
        "labelNames": ["No", "Yes"],
        "attrVals": {
            0:   ["vhigh", "high", "med", "low"],
            1:    ["vhigh", "high", "med", "low"],
            2:    ["2", "3", "4", "5more"],
            3:  ["2", "4", "more"],
            4: ["small", "med", "big"],
            5:   ["low", "med", "high"],
        },
        "labelType": str,
        "maxTreeDepths": np.arange(6),
    },
    "bank": {
        "trainPath": "./bank/train.csv",
        "testPath": "./bank/test.csv",
        "attrNames": ["age","job","marital","education","default","balance","housing","loan","contact","day","month","duration","campaign","pdays","previous","poutcome"],
        "labelNames": ["No", "Yes"],
        "categoricalAttrs": [1,2,3,4,6,7,8,10,15],
        "numericalAttrs": [0,5,9,11,12,13,14],
        "attrVals": {
            1:   ["admin.","unknown","unemployed","management","housemaid","entrepreneur","student","blue-collar","self-employed","retired","technician","services"],
            2:    ["married","divorced","single"],
            3:    ["unknown","secondary","primary","tertiary"],
            4:  ["yes","no"],
            6: ["yes","no"],
            7:   ["yes","no"],
            8:   ["unknown","telephone","cellular"],
            10:    ["jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"],
            15:    ["unknown","other","failure","success"],
        },
        "labelType": str,
        "maxTreeDepths": np.arange(16),
    },
}